services:
  # Load balancer
  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - payment-processor
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  # API instances
  api1:
    build: .
    hostname: api1
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=8080
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - internal
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  api2:
    build: .
    hostname: api2
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=8080
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - internal
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  # Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "25MB"

  # Redis for queue
  redis:
    image: redis:7-alpine
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "6MB"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge
  internal:
    driver: bridge
