x-service-templates:
  backend: &backend
    image: ghcr.io/krymancer/rinha-2025-01-zig:main
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    healthcheck:
      test:  wget --no-verbose --tries=1 --spider http://0.0.0.0:8080/health || exit 1
      start_period: 1s
      timeout: 5s
      interval: 5s
      retries: 3

services:
  backend-1:
    <<: *backend
    hostname: backend-1

  backend-2:
    <<: *backend
    hostname: backend-2

  haproxy:
    image: haproxy:alpine
    volumes:
      - .config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
    ports:
      - "9999:80"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"
    networks:
      - payment-processor
      - backend

networks:
  payment-processor:
    external: true
  backend:
