services:
  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "9999:9999"
    volumes:
      - .config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - payment-processor
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  api1:
    build: .
    hostname: api1
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=8080
    depends_on:
      - db
    networks:
      - internal
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "160MB"

  api2:
    build: .
    hostname: api2
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=8080
    depends_on: 
      - db
    networks:
      - internal
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "160MB"
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge
  internal:
    driver: bridge
