x-service-templates:
  backend: &backend
    image: ghcr.io/krymancer/rinha-2025-01-zig:main
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
    healthcheck:
      test:  wget --no-verbose --tries=1 --spider http://0.0.0.0:8080/health || exit 1

services:
  backend-1:
    <<: *backend
    hostname: backend-1

  backend-2:
    <<: *backend
    hostname: backend-2

  nginx:
    image: nginx:alpine
    volumes:
      - .config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
    ports:
      - "9999:9999"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "40MB"
    networks:
      - payment-processor
      - backend

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --maxmemory 64mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "70MB"
    networks:
      - backend

networks:
  payment-processor:
    external: true
  backend:
